### ISSUE TITLE
Use default checkout path

### ISSUE THREAD

**Issue by GMNGeoffrey** [hasura/smooth-checkout-buildkite-plugin#13]
I'm interested in using this plugin to check out a different branch than the default (which seems like something Buildkite itself should make configurable, but no matter). I *don't* want the behavior of creating new checkout directories per build though. That seems like unnecessary overhead and I don't think the explanation of it is correct. Buildkite uses the *agent* id, not the hostname, for the directory name, so if you've got multiple agents on the same host, they will use different directories (in fact this is a bit annoying sometimes because if you change the agent name you end up with orphaned directories using up disk space). Here's an example build that's running on a VM that has 4 agents configured with spawn: https://buildkite.com/llvm-project/upstream-bazel-rbe/builds/5658. Note that the working directory is the same as the agent name (I can tell you that is not the hostname). If you want to configure the build path per-agent you can also set that with https://buildkite.com/docs/agent/v3/configuration#build-path (note that will not be dynamic per job).

So I'd like to either 1) remove the custom checkout directory entirely, or if you still have some use for it 2) make it optional. Happy to send a PR

**Comment by scriptnull** [comment]
Hi, thanks for opening up this issue! (and sorry that I missed this earlier)

We have been thinking about removing the folder creation logic from this repo and instead do the following
- By default, path will be `BUILDKITE_BUILD_CHECKOUT_PATH`
- Introduce a parameter in the config that accepts the path to use explicitly. (if mentioned, this will be preferred for cloning instead of `BUILDKITE_BUILD_CHECKOUT_PATH`)

(how does the above idea sound? We are happy to accept contributions for this as well!) 

One thing the current folder structure gives is the idea of which job left residue on the build machines if something goes wrong. Hence we prefer to continue using the same folder structure for our use-case.

We are also looking to introduce cloning of multiple repos at different paths (we may choose to do the above-said refactoring alongside it if not now).

**Comment by GMNGeoffrey** [comment]
We're not prioritizing our Buildkite migration this quarter :-/ So it will be a while till I come back to it. I think I concluded that it would be best to avoid a plugin here and just manually get a different branch, but when I revisit this I may be able to offer a more thoughtful response. Using `BUILDKITE_BUILD_CHECKOUT_PATH` seems like a good plan, on its face. I understand the concern about leaving the machines pristine afterwards (and it makes sense for this to be an option), but for now I've had more issues where I want the speed than the purity of cleaning things up after.

**Comment by GMNGeoffrey** [comment]
I'm back! I now have some time to focus on rebasing our project automation on Buildkite. I'm still interested in this plugin. My use case is modifying the checkout to fetch the upstream repository default branch when running on PRs to use some configuration from there to vet whether it's OK to run code from the PR. One issue I ran into with this plugin is that it uses sudo, which by default requires password entry. Obviously could set up passwordless sudo, but I don't think I really want that.

I still like your suggestion to default to `BUILDKITE_BUILD_CHECKOUT_PATH`. I think a tricky thing about allowing it to be explicitly set is that you're not going to be able to use the job-id for that, since it's not known until the job is running and if you use upload-pipeline then you have a different job!

I could take a look at contributing something here, but per Google policy in order to do that, this project would need to have some license (e.g. Apache2, MIT, BSD)

**Comment by scriptnull** [comment]
Hi! Regarding `sudo`, we are tracking it in a separate issue [here](https://github.com/hasura/smooth-checkout-buildkite-plugin/issues/21) (it has given us problems too and we would like to get rid of it at some point).

Regarding the LICENSE part, I just added [one](https://github.com/hasura/smooth-checkout-buildkite-plugin/blob/main/LICENSE) :) 

I think for your use-case, something like the below might be the starting point:

```yaml
steps:
  - command: echo "Checks out repo at given ref"
    plugins:
      - hasura/smooth-checkout#v3.1.0:
          repos:
            - config:
              - url: git@github.com:<username>/<reponame>.git
                ref: <default-branch-name>
```

I lost track of ideas around the CHECKOUT path. I notice that @imperfect-fourth had opened a PR touching it here https://github.com/hasura/smooth-checkout-buildkite-plugin/pull/24 - I will probably discuss with them regarding the motivation of it and to gather more ideas around what we can do here.

**Comment by GMNGeoffrey** [comment]
Thanks. I sent https://github.com/hasura/smooth-checkout-buildkite-plugin/pull/25
